- id: 1
  name: Cinnamon Rolls
  price: 10.00
  weight: 500
  description: 10 Homemade fresh cinnamon rolls
  image: lovelee-cinnamon-rolls-2.jpg

- id: 2
  name: Coffee
  price: 15.00
  weight: 750
  description: 1 lb. of savory whole bean coffee
  image: coffee-beans.jpg

- id: 3
  name: Pumpkin Cinnamon Rolls
  price: 15.00
  weight: 500
  description: 10 Homemade fresh pumpkin cinnamon rolls
  image: lovelee-cinnamon-rolls-2.jpg
